### ISSUE TITLE
HTTPS Certificate has expired

### ISSUE THREAD

**Issue by bhargavgv** [GoogleChromeLabs/sample-currency-converter#9]
The certificate for the material.money site has expired.

**Comment by 7samurai** [comment]
+1 App is no more useable

**Comment by 7samurai** [comment]
Yes, for the page, and the PWA works not normal.

**Comment by grigs** [comment]
@mustafa-x I included this app in my upcoming book on Progressive Web Apps because it is a great example of offline UX notifying someone that content is out of date. The copy editor found the expired certificate and we may have to pull it out of the book because of the certificate making it seem seem like we're routing people to a dangerous site.

So I wondered if there was any update on this? I'd love to keep the site in the book because I haven't been able to find another clear example of a UI that notifies users of out of date information. Thanks for creating a great example. :)

**Comment by mustafa-x** [comment]
opps sorry, I dropped the ball on this one, let me take a look at it.

**Comment by mustafa-x** [comment]
Still chasing this, sorry for the delay.

**Comment by mustafa-x** [comment]
Should be fixed now - https://material.money/
